# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0Z_AVQ_DpK62G1XNpY6jgoB6ZpwvWWA
"""

!pip install bardapi

from bardapi import Bard
import os
import time

# Replace XXXX with the values you get from __Secure-1PSID
key = str(input("Enter your key: "))
os.environ['_BARD_API_KEY']=key

Feild = str(input("Enter your Feild: "))
print("Let's sort out your doubts in ",Feild ,"feild")

# Set your input text
input_text = input("Enter your Question: ")

try:
  print(Bard().get_answer(input_text)['content'])
except Exception as e:
  print(f"An error occurred: {e}")

